# -*- encoding: utf-8 -*-
{
    'name': 'VoIP phonebook',
    'version': '1.0',
    'author': 'Odooist',
    'maintainer': 'Odooist',
    'price': 0,
    'currency': 'EUR',
    'support': 'odooist@gmail.com',
    'license': 'LGPL-3',
    'category': 'Phone',
    'summary': 'Make Odoo contacts available on your VoIP phones',
    'description': "",
    'data': [
        'views/atcom_template.xml',
        'views/cisco_template.xml',
        'views/digium_a_template.xml',
        'views/digium_d_template.xml',
        'views/gs_template.xml',
        'views/panasonic_template.xml',
        'views/polycom_template.xml',
        'views/snom_template.xml',
        'views/fanvil_template.xml',
        'views/yealink_template.xml',
        'views/res_partner.xml',
        'views/settings.xml',
        ],
    'demo': [
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'images': ['static/description/gs.png'],
}
